"""
db.py — Epistemic Graph data access layer
Pure Python stdlib sqlite3. No ORM. Returns plain dicts.
Generated by Devstral (mistralai/devstral-small-2-2512), assembled by Automator.
"""

import sqlite3
import json
import time
from typing import Optional, Any


def _ts() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%S")


def init_db(db_path: str) -> sqlite3.Connection:
    """Create all tables and return an open connection with row_factory set."""
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    c = conn.cursor()

    c.execute("""
    CREATE TABLE IF NOT EXISTS research_objects (
        id          INTEGER PRIMARY KEY,
        name        TEXT NOT NULL,
        description TEXT,
        created_at  TEXT NOT NULL,
        updated_at  TEXT NOT NULL
    )""")

    c.execute("""
    CREATE TABLE IF NOT EXISTS nodes (
        id                 INTEGER PRIMARY KEY,
        research_object_id INTEGER NOT NULL REFERENCES research_objects(id),
        type               TEXT NOT NULL,
        title              TEXT,
        body               TEXT,
        type_metadata      TEXT NOT NULL DEFAULT '{}',
        created_at         TEXT NOT NULL,
        updated_at         TEXT NOT NULL
    )""")

    c.execute("""
    CREATE TABLE IF NOT EXISTS edges (
        id           INTEGER PRIMARY KEY,
        from_node_id INTEGER NOT NULL REFERENCES nodes(id),
        to_node_id   INTEGER NOT NULL REFERENCES nodes(id),
        relationship TEXT NOT NULL,
        label        TEXT DEFAULT '',
        created_at   TEXT NOT NULL
    )""")

    c.execute("""
    CREATE TABLE IF NOT EXISTS documents (
        id                 INTEGER PRIMARY KEY,
        research_object_id INTEGER NOT NULL REFERENCES research_objects(id),
        title              TEXT NOT NULL,
        source_url         TEXT,
        filename           TEXT,
        extracted_text     TEXT,
        created_at         TEXT NOT NULL
    )""")

    c.execute("""
    CREATE TABLE IF NOT EXISTS node_documents (
        node_id     INTEGER NOT NULL REFERENCES nodes(id),
        document_id INTEGER NOT NULL REFERENCES documents(id),
        PRIMARY KEY (node_id, document_id)
    )""")

    # Indexes
    c.execute("CREATE INDEX IF NOT EXISTS idx_nodes_ro ON nodes(research_object_id)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_nodes_type ON nodes(type)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_edges_from ON edges(from_node_id)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_edges_to ON edges(to_node_id)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_docs_ro ON documents(research_object_id)")

    conn.commit()
    return conn


# ── Research Objects ──────────────────────────────────────────────────────────

def create_research_object(db: sqlite3.Connection, name: str, description: str = "") -> int:
    """Insert a new research object, return its id."""
    ts = _ts()
    cur = db.execute(
        "INSERT INTO research_objects (name, description, created_at, updated_at) VALUES (?,?,?,?)",
        (name, description, ts, ts)
    )
    db.commit()
    return cur.lastrowid


def get_research_object(db: sqlite3.Connection, id: int) -> Optional[dict]:
    """Fetch a single research object by id."""
    row = db.execute("SELECT * FROM research_objects WHERE id=?", (id,)).fetchone()
    return dict(row) if row else None


def list_research_objects(db: sqlite3.Connection) -> list[dict]:
    """Return all research objects."""
    rows = db.execute("SELECT * FROM research_objects ORDER BY created_at DESC").fetchall()
    return [dict(r) for r in rows]


def update_research_object(db: sqlite3.Connection, id: int, **fields) -> bool:
    """Update name/description of a research object."""
    if not fields:
        return False
    fields["updated_at"] = _ts()
    sets = ", ".join(f"{k}=?" for k in fields)
    vals = list(fields.values()) + [id]
    cur = db.execute(f"UPDATE research_objects SET {sets} WHERE id=?", vals)
    db.commit()
    return cur.rowcount > 0


# ── Nodes ─────────────────────────────────────────────────────────────────────

def create_node(db: sqlite3.Connection, research_object_id: int, type: str,
                title: str, body: str, type_metadata: dict) -> int:
    """Insert a typed node, return its id. type_metadata is stored as JSON."""
    ts = _ts()
    cur = db.execute(
        """INSERT INTO nodes
           (research_object_id, type, title, body, type_metadata, created_at, updated_at)
           VALUES (?,?,?,?,?,?,?)""",
        (research_object_id, type, title, body, json.dumps(type_metadata), ts, ts)
    )
    db.commit()
    return cur.lastrowid


def get_node(db: sqlite3.Connection, id: int) -> Optional[dict]:
    """Fetch a single node; type_metadata is parsed from JSON."""
    row = db.execute("SELECT * FROM nodes WHERE id=?", (id,)).fetchone()
    if not row:
        return None
    d = dict(row)
    d["type_metadata"] = json.loads(d["type_metadata"] or "{}")
    return d


def list_nodes(db: sqlite3.Connection, research_object_id: int,
               type: Optional[str] = None) -> list[dict]:
    """List nodes for a research object, optionally filtered by type."""
    if type:
        rows = db.execute(
            "SELECT * FROM nodes WHERE research_object_id=? AND type=? ORDER BY created_at",
            (research_object_id, type)
        ).fetchall()
    else:
        rows = db.execute(
            "SELECT * FROM nodes WHERE research_object_id=? ORDER BY created_at",
            (research_object_id,)
        ).fetchall()
    result = []
    for r in rows:
        d = dict(r)
        d["type_metadata"] = json.loads(d["type_metadata"] or "{}")
        result.append(d)
    return result


def update_node(db: sqlite3.Connection, id: int, **fields) -> bool:
    """Update arbitrary node fields. type_metadata dict auto-serialised to JSON."""
    if not fields:
        return False
    if "type_metadata" in fields:
        fields["type_metadata"] = json.dumps(fields["type_metadata"])
    fields["updated_at"] = _ts()
    sets = ", ".join(f"{k}=?" for k in fields)
    vals = list(fields.values()) + [id]
    cur = db.execute(f"UPDATE nodes SET {sets} WHERE id=?", vals)
    db.commit()
    return cur.rowcount > 0


def delete_node(db: sqlite3.Connection, id: int) -> bool:
    """Delete a node and its edges."""
    db.execute("DELETE FROM edges WHERE from_node_id=? OR to_node_id=?", (id, id))
    db.execute("DELETE FROM node_documents WHERE node_id=?", (id,))
    cur = db.execute("DELETE FROM nodes WHERE id=?", (id,))
    db.commit()
    return cur.rowcount > 0


# ── Edges ─────────────────────────────────────────────────────────────────────

def create_edge(db: sqlite3.Connection, from_node_id: int, to_node_id: int,
                relationship: str, label: str = "") -> int:
    """Create a typed directed edge between two nodes."""
    cur = db.execute(
        "INSERT INTO edges (from_node_id, to_node_id, relationship, label, created_at) VALUES (?,?,?,?,?)",
        (from_node_id, to_node_id, relationship, label, _ts())
    )
    db.commit()
    return cur.lastrowid


def get_edges(db: sqlite3.Connection, node_id: int) -> dict:
    """Return outgoing and incoming edges for a node."""
    out_rows = db.execute("SELECT * FROM edges WHERE from_node_id=?", (node_id,)).fetchall()
    in_rows  = db.execute("SELECT * FROM edges WHERE to_node_id=?",   (node_id,)).fetchall()
    return {
        "outgoing": [dict(r) for r in out_rows],
        "incoming": [dict(r) for r in in_rows],
    }


def delete_edge(db: sqlite3.Connection, id: int) -> bool:
    """Delete an edge by id."""
    cur = db.execute("DELETE FROM edges WHERE id=?", (id,))
    db.commit()
    return cur.rowcount > 0


# ── Documents ─────────────────────────────────────────────────────────────────

def list_all_edges(db: sqlite3.Connection, research_object_id: int) -> list[dict]:
    """Return all edges between nodes belonging to a research object."""
    rows = db.execute(
        """
        SELECT e.* FROM edges e
        JOIN nodes fn ON e.from_node_id = fn.id
        WHERE fn.research_object_id = ?
        ORDER BY e.created_at
        """,
        (research_object_id,)
    ).fetchall()
    return [dict(r) for r in rows]


def add_document(db: sqlite3.Connection, research_object_id: int, title: str,
                 source_url: str = "", filename: str = "",
                 extracted_text: str = "") -> int:
    """Attach a document (PDF, arXiv paper, etc.) to a research object."""
    cur = db.execute(
        """INSERT INTO documents
           (research_object_id, title, source_url, filename, extracted_text, created_at)
           VALUES (?,?,?,?,?,?)""",
        (research_object_id, title, source_url, filename, extracted_text, _ts())
    )
    db.commit()
    return cur.lastrowid


def get_document(db: sqlite3.Connection, id: int) -> Optional[dict]:
    """Fetch a document by id."""
    row = db.execute("SELECT * FROM documents WHERE id=?", (id,)).fetchone()
    return dict(row) if row else None


def list_documents(db: sqlite3.Connection, research_object_id: int) -> list[dict]:
    """List all documents attached to a research object."""
    rows = db.execute(
        "SELECT id, title, source_url, filename, created_at FROM documents WHERE research_object_id=? ORDER BY created_at",
        (research_object_id,)
    ).fetchall()
    return [dict(r) for r in rows]


def link_node_document(db: sqlite3.Connection, node_id: int, document_id: int) -> bool:
    """Link a node to a document (many-to-many). Ignores duplicate."""
    try:
        db.execute("INSERT INTO node_documents (node_id, document_id) VALUES (?,?)",
                   (node_id, document_id))
        db.commit()
        return True
    except sqlite3.IntegrityError:
        return False


def get_node_documents(db: sqlite3.Connection, node_id: int) -> list[dict]:
    """Return all documents linked to a node."""
    rows = db.execute(
        """SELECT d.id, d.title, d.source_url, d.filename, d.created_at
           FROM documents d
           JOIN node_documents nd ON d.id = nd.document_id
           WHERE nd.node_id = ?""",
        (node_id,)
    ).fetchall()
    return [dict(r) for r in rows]
